# Generated by Django 3.0.5 on 2020-10-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amazon_Price_Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asin', models.CharField(max_length=10)),
                ('Description', models.TextField()),
                ('Start_time', models.DateField(default='')),
                ('End_time', models.DateField(default='')),
                ('F3', models.TextField()),
                ('A6', models.TimeField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F1', models.CharField(max_length=20)),
                ('F2', models.CharField(choices=[('A', 'ablitity'), ('B', 'baby')], default='A', max_length=3)),
                ('F3', models.TextField()),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore')], default='FR', max_length=2)),
                ('Start_date', models.DateField(default='')),
                ('End_date', models.DateField(default='')),
                ('Start_time', models.DateTimeField(default='')),
                ('End_time', models.DateTimeField(default='')),
                ('A3', models.DateTimeField(default='')),
                ('A5', models.TimeField(default='')),
                ('A6', models.TimeField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
