# Generated by Django 3.0.5 on 2020-09-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_amazon_price_tracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F1', models.CharField(max_length=20)),
                ('F2', models.TextField()),
                ('F3', models.TextField()),
            ],
        ),
    ]
