# Generated by Django 3.1.1 on 2021-04-05 09:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASIN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ASIN_Search_task',
            fields=[
                ('ASIN_Search_task_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ASIN_Search_List', models.CharField(default='a1-', max_length=63)),
                ('Number_Of_Result', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10)),
                ('Start_Time', models.DateTimeField(default=datetime.datetime.now)),
                ('End_Time', models.DateTimeField(default=datetime.datetime.now)),
                ('Request_Status', models.CharField(choices=[('Ready', 'Ready'), ('Ongoing', 'Ongoing'), ('Complete', 'Complete'), ('Error', 'Error')], max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='ASIN_task',
            fields=[
                ('ASIN_task_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ASIN_Name_List', models.CharField(default='a1-', max_length=63)),
                ('Request_Description', models.CharField(default='b1-', max_length=63)),
                ('Periodicity', models.CharField(choices=[('Once', 'Once'), ('Perodic', 'Perodic')], max_length=63)),
                ('Start_Time', models.DateTimeField(default=datetime.datetime.now)),
                ('Interval', models.DurationField(default=datetime.timedelta(seconds=5))),
                ('End_Time', models.DateTimeField(default=datetime.datetime.now)),
                ('Request_Status', models.CharField(choices=[('Ready', 'Ready'), ('Ongoing', 'Ongoing'), ('Complete', 'Complete'), ('Error', 'Error')], max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_if', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1300)),
                ('clinic_name', models.CharField(max_length=1300)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('submitted_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ASIN_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='download.asin')),
            ],
        ),
    ]
