# Generated by Django 3.1.1 on 2021-03-01 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asin_task',
            name='End_time',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='asin_task',
            name='Start_time',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
