# Generated by Django 3.1.1 on 2021-03-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0003_auto_20210228_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asin_task',
            name='request_status',
            field=models.CharField(choices=[('1', 'Ready'), ('2', 'Ongoing'), ('3', 'Complete'), ('4', 'Error')], max_length=63),
        ),
    ]
