# Generated by Django 3.1.1 on 2021-03-01 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0004_auto_20210301_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asin_task',
            name='Start_time',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='asin_task',
            name='request_status',
            field=models.CharField(choices=[('Ready', 'Ready'), ('Ongoing', 'Ongoing'), ('Complete', 'Complete'), ('Error', 'Error')], max_length=63),
        ),
    ]
