# Generated by Django 3.1.1 on 2021-03-02 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0005_auto_20210301_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asin_task',
            old_name='asin_name_list',
            new_name='Asin_Name_List',
        ),
        migrations.RenameField(
            model_name='asin_task',
            old_name='End_time',
            new_name='End_Time',
        ),
        migrations.RenameField(
            model_name='asin_task',
            old_name='request_description',
            new_name='Request_Description',
        ),
        migrations.RenameField(
            model_name='asin_task',
            old_name='request_status',
            new_name='Request_Status',
        ),
        migrations.RenameField(
            model_name='asin_task',
            old_name='Start_time',
            new_name='Start_Time',
        ),
    ]
