# Generated by Django 3.1.1 on 2021-03-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0006_auto_20210301_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asin_task',
            old_name='Asin_Name_List',
            new_name='ASIN_Name_List',
        ),
    ]
