# Generated by Django 3.1.1 on 2021-03-11 06:21

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0007_auto_20210301_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASIN_Search_task',
            fields=[
                ('ASIN_Search_task_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ASIN_Search_List', models.CharField(default='a1-', max_length=63)),
                ('Number_Of_Result', models.IntegerField(choices=[('Ready', 'Ready'), ('Ongoing', 'Ongoing'), ('Complete', 'Complete'), ('Error', 'Error')], default=10)),
                ('Start_Time', models.DateField(default=datetime.date.today)),
                ('End_Time', models.DateField(default=datetime.datetime.now)),
                ('Request_Status', models.CharField(choices=[('Ready', 'Ready'), ('Ongoing', 'Ongoing'), ('Complete', 'Complete'), ('Error', 'Error')], max_length=63)),
            ],
        ),
        migrations.AlterField(
            model_name='asin_task',
            name='Request_Status',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=63),
        ),
    ]
